const EmberServer = require('node-emberplus').EmberServer
const { ParameterType, FunctionArgument } = require('node-emberplus').EmberLib

const targets = [
    'tgt1',
    'tgt2',
    'tgt3',
    'tgt4',
    'tgt5',
    'tgt6',
    'tgt7',
    'tgt8',
    'tgt9',
    'tgt10',
    'tgt11',
    'tgt12',
    'tgt13',
    'tgt14',
    'tgt15',
    'tgt16',
    'tgt17',
    'tgt18',
    'tgt19',
    'tgt20',
    'tgt21',
    'tgt22',
    'tgt23',
    'tgt24',
    'tgt25',
    'tgt26',
    'tgt27',
    'tgt28',
    'tgt29',
    'tgt30',
    'tgt31',
    'tgt32',
    'tgt33',
    'tgt34',
    'tgt35',
    'tgt36',
    'tgt37',
    'tgt38',
    'tgt39',
    'tgt40',
    'tgt41',
    'tgt42',
    'tgt43',
    'tgt44',
    'tgt45',
    'tgt46',
    'tgt47',
    'tgt48',
    'tgt49',
    'tgt50',
    'tgt51',
    'tgt52',
    'tgt53',
    'tgt54',
    'tgt55',
    'tgt56',
    'tgt57',
    'tgt58',
    'tgt59',
    'tgt60',
    'tgt61',
    'tgt62',
    'tgt63',
    'tgt64',
    'tgt65',
    'tgt66',
    'tgt67',
    'tgt68',
    'tgt69',
    'tgt70',
    'tgt71',
    'tgt72',
    'tgt73',
    'tgt74',
    'tgt75',
    'tgt76',
    'tgt77',
    'tgt78',
    'tgt79',
    'tgt80',
    'tgt81',
    'tgt82',
    'tgt83',
    'tgt84',
    'tgt85',
    'tgt86',
    'tgt87',
    'tgt88',
    'tgt89',
    'tgt90',
    'tgt91',
    'tgt92',
    'tgt93',
    'tgt94',
    'tgt95',
    'tgt96',
    'tgt97',
    'tgt98',
    'tgt99',
]
const sources = [
    'src1',
    'src2',
    'src3',
    'src4',
    'src5',
    'src6',
    'src7',
    'src8',
    'src9',
    'src10',
    'src11',
    'src12',
    'src13',
    'src14',
    'src15',
    'src16',
    'src17',
    'src18',
    'src19',
    'src20',
    'src21',
    'src22',
    'src23',
    'src24',
    'src25',
    'src26',
    'src27',
    'src28',
    'src29',
    'src30',
    'src31',
    'src32',
    'src33',
    'src34',
    'src35',
    'src36',
    'src37',
    'src38',
    'src39',
    'src40',
    'src41',
    'src42',
    'src43',
    'src44',
    'src45',
    'src46',
    'src47',
    'src48',
    'src49',
    'src50',
    'src51',
    'src52',
    'src53',
    'src54',
    'src55',
    'src56',
    'src57',
    'src58',
    'src69',
    'src60',
    'src61',
    'src62',
    'src63',
    'src64',
    'src65',
    'src66',
    'src67',
    'src68',
    'src69',
    'src70',
    'src71',
    'src72',
    'src73',
    'src74',
    'src75',
    'src76',
    'src77',
    'src78',
    'src79',
    'src80',
    'src81',
    'src82',
    'src83',
    'src84',
    'src85',
    'src86',
    'src87',
    'src88',
    'src89',
    'src90',
    'src91',
    'src92',
    'src93',
    'src94',
    'src95',
    'src96',
    'src97',
    'src98',
    'src99'
]
const defaultSources = [
    { identifier: 't-0', value: -1, access: 'readWrite' },
    { identifier: 't-1', value: 0, access: 'readWrite' },
    { identifier: 't-2', value: 0, access: 'readWrite' },
]
const labels = function (endpoints: any, type: any) {
    let labelArray = []
    for (let i = 0; i < endpoints.length; i++) {
        let endpoint = endpoints[i]
        let l = { identifier: `${type}-${i}` }
        if (endpoint) {
            //@ts-ignore
            l.value = endpoint
        }
        labelArray.push(l)
    }
    return labelArray
}

const buildConnections = function (s: any, t: any) {
    let connections = []
    for (let i = 0; i < t.length; i++) {
        connections.push({ target: `${i}` })
    }
    return connections
}
const jsonTree = [
    {
        // path "0"
        identifier: 'Sofie Portal',
        children: [
            {
                // path "0.0"
                identifier: 'identity',
                children: [
                    { identifier: 'product', value: 'Sofie Portal' },
                    {
                        identifier: 'company',
                        value: 'TV2 DK',
                        access: 'readWrite',
                    },
                ],
            },
            {
                // path "0.1"
                identifier: 'router',
                children: [
                    {
                        // path 0.1.0
                        identifier: 'PortalMatrix',
                        type: 'oneToN',
                        mode: 'linear',
                        targetCount: targets.length,
                        sourceCount: sources.length,
                        connections: buildConnections(sources, targets)
                    }
                ],
            },
        ],
    },
]
export const root = EmberServer.JSONtoTree(jsonTree)
